# Generated by Django 4.2.2 on 2023-06-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='first_name',
            field=models.CharField(default='anyname', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='last_name',
            field=models.CharField(default='nonename', max_length=20),
            preserve_default=False,
        ),
    ]
