# Generated by Django 4.2.2 on 2023-06-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_agent_first_name_agent_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='last_name',
        ),
    ]
