# Generated by Django 4.2.2 on 2023-06-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_agent_first_name_remove_agent_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default='lead@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(default=44, max_length=20),
        ),
    ]
